serial:
  input:
    port: ${SERIAL_INPUT_PORT:COM7}
    baudRate: ${SERIAL_INPUT_BAUD:9600}
    slaveId: ${SERIAL_INPUT_SLAVE:1}
    startOffset: ${SERIAL_INPUT_OFFSET:0}
    pollInterval: ${SERIAL_INPUT_POLL:1000}
    numberOfRegisters: ${SERIAL_INPUT_REGS:72}

  output:
    port: ${SERIAL_OUTPUT_PORT:COM11}
    baudRate: ${SERIAL_OUTPUT_BAUD:9600}
    slaveId: ${SERIAL_OUTPUT_SLAVE:1}
    startOffset: ${SERIAL_OUTPUT_OFFSET:0}
    pollInterval: ${SERIAL_OUTPUT_POLL:1000}

server:
  port: ${SERVER_PORT:8888}

solis:
  api:
    id: ${SOLIS_API_ID}
    secret: ${SOLIS_API_SECRET}
    sn: ${SOLIS_API_SN}
    timezone: ${SOLIS_TIMEZONE:3}