serial:
  input:
    port: ${SERIAL_INPUT_PORT:COM7}
    baudRate: ${SERIAL_INPUT_BAUD:9600}
    slaveId: ${SERIAL_INPUT_SLAVE:1}
    startOffset: ${SERIAL_INPUT_OFFSET:0}
    pollInterval: ${SERIAL_INPUT_POLL:1000}
    numberOfRegisters: ${SERIAL_INPUT_REGS:72}
    # delay before first attempt (ms) — helps after hard restarts on Windows
    initialOpenDelayMs: ${SERIAL_INITIAL_OPEN_DELAY_MS:2000}
    # extra backoff after a failed read/open (ms)
    reopenBackoffMs: ${SERIAL_REOPEN_BACKOFF_MS:2000}
    warmupMs: ${SERIAL_WARMUP_MS:2000}
    timeoutsBeforeReopen: ${SERIAL_TIMEOUTS_BEFORE_REOPEN:3}

  output:
    port: ${SERIAL_OUTPUT_PORT:COM11}
    baudRate: ${SERIAL_OUTPUT_BAUD:9600}
    slaveId: ${SERIAL_OUTPUT_SLAVE:1}
    startOffset: ${SERIAL_OUTPUT_OFFSET:0}
    pollInterval: ${SERIAL_OUTPUT_POLL:1000}

devtools:
  restart:
    enabled: false
  livereload:
    enabled: false

server:
  port: ${SERVER_PORT:8888}           # UI
  address: ${SERVER_ADDRESS:0.0.0.0}  # UI reachable on LAN/Tailscale

solis:
  api:
    id: ${SOLIS_API_ID}
    secret: ${SOLIS_API_SECRET}
    sn: ${SOLIS_API_SN}
    uri: ${SOLIS_URI}
  fetch:
    periodSeconds: ${SOLIS_FETCH_PERIOD_SECONDS:10}     # how often to call Solis API
  minImportKw: ${SOLIS_MIN_IMPORT_KW:0.2}               # ignore grid import below this (deadband)
  maxDataAgeMs: ${SOLIS_MAX_DATA_AGE_MS:300000}         # if no API updates for this long, treat delta as 0
  smoothingFactor: ${SOLIS_SMOOTHING_FACTOR:0.8}        # 0..1 (1.0 = no smoothing)
  # compensation switch (default ON). Can be overridden by env SOLIS_OVERRIDE_ENABLED=true/false
  overrideEnabled: ${SOLIS_OVERRIDE_ENABLED:true}

logging:
  level:
    com:
      elssolution:
        smartmetrapp: ${SMARTMETER_LOG_LEVEL:INFO}

smartmetr:
  cosPhiMin: ${SMARTMETR_COSPHI_MIN:0.85}
  smoothingWindow: ${SMARTMETR_SMOOTHING_WINDOW:5}
  deltaMaxKwPerSec: ${SMARTMETR_DELTA_MAX_KW_PER_SEC:2}
  clamp:
    minKw: ${SMARTMETR_CLAMP_MIN_KW:0}
    maxKw: ${SMARTMETR_CLAMP_MAX_KW:50}
  staleToZeroMs: ${SMARTMETR_STALE_TO_ZERO_MS:300000}
  rampDownMs: ${SMARTMETR_RAMP_DOWN_MS:2000}
  floatOrder: ${SMARTMETR_FLOAT_ORDER:BE}

management:
  endpoints:
    web:
      base-path: ${MANAGEMENT_BASE_PATH:/_manage}
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:never}
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
    git:
      mode: full

meterMap:
  vL1:    ${METERMAP_VL1:0}
  iL1:    ${METERMAP_IL1:6}
  pTotal: ${METERMAP_PTOTAL:52}
  vL2:    ${METERMAP_VL2:2}
  vL3:    ${METERMAP_VL3:4}
  iL2:    ${METERMAP_IL2:8}
  iL3:    ${METERMAP_IL3:10}
  pL1:    ${METERMAP_PL1:12}
  pL2:    ${METERMAP_PL2:14}
  pL3:    ${METERMAP_PL3:16}

alert:
  telegram:
    enabled: ${ALERT_TELEGRAM_ENABLED:false}
    botToken: ${ALERT_TELEGRAM_BOT_TOKEN:}
    chatIds: ${ALERT_TELEGRAM_CHAT_IDS:}
    cooldownMs: ${ALERT_TELEGRAM_COOLDOWN_MS:900000}  # 15 min
    prefix: ${ALERT_TELEGRAM_PREFIX:}       # "Winston Churchill — Solis 50kW"
    startupPing: ${ALERT_TELEGRAM_STARTUP_PING:true}
    shutdownPing: ${ALERT_TELEGRAM_SHUTDOWN_PING:true}
    heartbeat:
      enabled: ${ALERT_TELEGRAM_HEARTBEAT_ENABLED:true}
      cron: "0 0 10 * * *"   # every day 10:00 local time