serial:
  input:
    port: ${SERIAL_INPUT_PORT:COM7}
    baudRate: ${SERIAL_INPUT_BAUD:9600}
    slaveId: ${SERIAL_INPUT_SLAVE:1}
    startOffset: ${SERIAL_INPUT_OFFSET:0}
    pollInterval: ${SERIAL_INPUT_POLL:1000}
    numberOfRegisters: ${SERIAL_INPUT_REGS:72}

  output:
    port: ${SERIAL_OUTPUT_PORT:COM11}
    baudRate: ${SERIAL_OUTPUT_BAUD:9600}
    slaveId: ${SERIAL_OUTPUT_SLAVE:1}
    startOffset: ${SERIAL_OUTPUT_OFFSET:0}
    pollInterval: ${SERIAL_OUTPUT_POLL:1000}

server:
  port: ${SERVER_PORT:8888}

solis:
  api:
    id: ${SOLIS_API_ID}
    secret: ${SOLIS_API_SECRET}
    sn: ${SOLIS_API_SN}
    uri: ${SOLIS_URI}
  fetch:
    periodSeconds: 10        # how often to call Solis API
  minImportKw: 0.2           # ignore grid import below this (deadband)
  maxDataAgeMs: 300000       # if no API updates for this long, treat delta as 0
  smoothingFactor: 0.8       # 0..1 (1.0 = no smoothing)
  # compensation switch (default ON). Can be overridden by env SOLIS_OVERRIDE_ENABLED=true/false
  overrideEnabled: ${SOLIS_OVERRIDE_ENABLED:true}

logging:
  level:
    com:
      elssolution:
        smartmetrapp: ${SMARTMETER_LOG_LEVEL:INFO}

smartmetr:
  cosPhiMin: 0.85
  smoothingWindow: 5
  deltaMaxKwPerSec: 2
  clamp:
    minKw: 0
    maxKw: 50
  staleToZeroMs: 300000
  rampDownMs: 2000
  floatOrder: BE

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized

alert:
  telegram:
    enabled: ${ALERT_TELEGRAM_ENABLED:false}
    botToken: ${ALERT_TELEGRAM_BOT_TOKEN:}
    chatId: ${ALERT_TELEGRAM_CHAT_ID:}
    cooldownMs: ${ALERT_TELEGRAM_COOLDOWN_MS:900000}  # 15 min